[system]
rtm_interval = 1  # sec
path_tmp = './tmp/'
restart_max = 10  # エラー時に何回までrestartする？

[bot]
res_default = '((☛(◜◔。◔◝)☚))ここ大丈夫ですか～～～？？？ '  # 未定義のコマンドに対する返答
res_img_default = 'ファイルを受け取ったけど何もしないぞ( ◠‿◠ )' # ファイル付き未定義コマンドに対する返答
res_help = '`コマンド 内容` でメンションしてください。e.g. `kill someone`'
res_kill_you = '思い上がるなよ、小童 (╬ ◠‿◠ )▄︻┻┳══━'
res_kill = 'いってくる ┗(☋｀ )┓'
res_tweet = 'tweetしました！'
res_toot = 'tootしました！'
cmd_sns = 'ttt'  # "tweet toot tsubuyaku!" 定義済の全SNSに投稿

[twitter]
url_post_media = 'https://upload.twitter.com/1.1/media/upload.json'
url_post_text = 'https://api.twitter.com/1.1/statuses/update.json'
url_oauth_request_token = 'https://twitter.com/oauth/request_token'
url_oauth_access_token = 'https://twitter.com/oauth/access_token'
url_oauth_authenticate = 'https://twitter.com/oauth/authorize'
url_oauth_callback = 'https://github.com/ebiiim'

[test]
img_url = 'https://www.google.co.jp/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
