[system]
rtm_interval = 1  # sec
path_tmp = './tmp/'
restart_max = 10  # エラー時に何回までrestartする？

[bot]
res_default = '((☛(◜◔。◔◝)☚))ここ大丈夫ですか～～～？？？ '  # 未定義のコマンドに対する返答
res_img_default = 'ファイルを受け取ったけど何もしないぞ( ◠‿◠ )' # ファイル付き未定義コマンドに対する返答
res_help = '`コマンド 内容` でメンションしてください。e.g. `kill someone`'
res_kill_you = '思い上がるなよ、小童 (╬ ◠‿◠ )▄︻┻┳══━'
res_kill = 'いってくる ┗(☋｀ )┓'
res_tweet = 'tweetしました！'
res_toot = 'tootしました！'
cmd_sns = 'ttt'  # "tsubuyaku tweet toot" つぶやき用コマンド
